### ISSUE TITLE
Unmute doesn't take fader position into account (mini)

### ISSUE THREAD

**Issue by fenarinarsa** [GoXLR-on-Linux/goxlr-utility#103]
When unmuting a channel, the channel's volume reverts to the value it was when muting, even if the fader was moved when the channel was muted.

Correct behavior should be to unmute to the fader's position volume.

Note: this behavior was also fixed in the official app

Version: 0.12.4 Windows, GoXLR mini

**Comment by FrostyCoolSlug** [comment]
Thanks for the report, when I did my testing they hadn't fixed this yet, so the mini behaviour was the same as the full size behaviour which is how it was implemented.

Testing on the latest version, you're right, it doesn't mess with the volumes anymore when the mute button is hit on a fader, I'll look into updating the util to match.

**Comment by FrostyCoolSlug** [comment]
The behaviour has been changed with bde544e and will come with the next release.

**Comment by fenarinarsa** [comment]
Thanks!! I'm looking forward to it, because I stopped using the official client. GoXLR utility has a big advantage over it, it doesn't crash when Windows goes out of sleep mode :)

**Comment by FrostyCoolSlug** [comment]
I've got a test build at https://github.com/GoXLR-on-Linux/goxlr-utility/suites/14344137562/artifacts/807561591 - could you give it a download and test for me please? Just to make sure it's all working right :)

**Comment by fenarinarsa** [comment]
> I've got a test build at https://github.com/GoXLR-on-Linux/goxlr-utility/suites/14344137562/artifacts/807561591 - could you give it a download and test for me please? Just to make sure it's all working right :)

Didn't test it thoroughly but it seems to work perfectly :)

**Comment by FrostyCoolSlug** [comment]
This fix is now released in 0.12.5, so closing the issue :)
