### ISSUE TITLE
[Question] - Voice effects on GoXLR Mini

### ISSUE THREAD

**Issue by Sirs0ri** [GoXLR-on-Linux/goxlr-utility#105]
Quick question, would this tool allow using the big GoXLR's voice effects on a GoXLR mini, or do the effects require extra hardware that the Mini simply doesn't have?

**Comment by JulanDeAlb** [comment]
Hey, as far as i know, the full size GoXLR does have all the effects on the device itself as hardware. That means the mini is lacking of the needed hardware
