### ISSUE TITLE
[Bug] .wav files in sample pad

### ISSUE THREAD

**Issue by ItsJogus** [GoXLR-on-Linux/goxlr-utility#109]
Hello,
Quickly to preface, I know nothing when it comes to coding or how this whole open source project works. I have though encountered an issue when moving over all my presets for the samples I had, all the .wav files that were recorded cannot be selected when trying to add them to the sample pad. I did notice that the .mp3 files did work though. Hopefully the .wav files can be used soon.

Thank you for dedicating your time to assure a product such as this one continues to work just as well or better than the original software.

**Comment by FrostyCoolSlug** [comment]
Looks like this has been tracked down, the problem occurs if you have the samples tab selected in the top right can you switch off and try again please (I have a fix prepped for the next release).

**Comment by ItsJogus** [comment]
Hey, apologies for not catching the emails in time. I did what was said, switching from the samples tab to the profiles tab and I was able to start adding the .wav files into my sample pad. Its a good thing you were able to get to the bottom of it.
Thank you for your work.
