### ISSUE TITLE
[Feature] Open Silently on Boot

### ISSUE THREAD

**Issue by kelseymcbratney** [GoXLR-on-Linux/goxlr-utility#113]
Hello! This is a fantastic utility and has been working great for me so far. I was curious if there was way to open the program on boot without opening the web interface. I am on Linux. Thanks for all your work!

**Comment by FrostyCoolSlug** [comment]
In Settings -> Utility Settings, there should be an 'Autostart on Login' button, which will just launch the daemon straight into the background when you login :)

**Comment by kelseymcbratney** [comment]
Thank you!! I misinterpreted the introductions and added it to startup within the Linux System Settings.
