### ISSUE TITLE
[Feature Request] import profiles

### ISSUE THREAD

**Issue by DannyDarth** [GoXLR-on-Linux/goxlr-utility#116]
Allows us to import profiles from our old go xlr app.

**Comment by lm41** [comment]
What do you mean by that. Currently the profiles are cross compatible. You can just copy them over.

**Comment by DannyDarth** [comment]
> What do you mean by that. Currently the profiles are cross compatible. You can just copy them over.

well i exported my profile from the main go xlr app but there is no option to import it to the go xlr utility.

**Comment by FrostyCoolSlug** [comment]
You can just copy the files over by hand. I'll look into adding an option to the installer to automate the process though.

**Comment by DannyDarth** [comment]
> You can just copy the files over by hand. I'll look into adding an option to the installer to automate the process though.

That would be nice. Ill look again but i dont see where i can copy them over to it.

**Comment by FrostyCoolSlug** [comment]
The instructions are on the main repo page.

You can quick access the utility's paths by right clicking on the system tray icon and selecting from the 'open paths' submenu, the official app stores the files in Documents/GoXLR, just copy the files between the locations.

**Comment by DannyDarth** [comment]
> The instructions are on the main repo page under "Getting Started".
> 
> You can quick access the utility's paths by right clicking on the system tray icon and selecting from the 'open paths' submenu, the official app stores the files in Documents/GoXLR, just copy the files between the locations.

That worked thanks. All this needs now is the ability to click on each part of the go xlr and itll be just about the same as the actual app.
