### ISSUE TITLE
[Bug] Systray Icon Does Not Persist After a Windows Explorer Crash/Restart

### ISSUE THREAD

**Issue by anthonybaldwin** [GoXLR-on-Linux/goxlr-utility#124]
**OS**: Windows 11 22H2

**Expected**: Systray icon persists after a Windows Explorer crash/restart
**Actual**: Systray icon is not present after a Windows Explorer crash/restart

---

**Steps to recreate**:
(**Pre-req**: GoXLR Utility running w/ systray icon present)

1. Open Task Manager and search for `Windows Explorer`, then right click and restart
1. 🐛 See the icon is no longer present in systray
1. In Task Manager again search for `goxlr-daemon.exe`, then right click and end the task
1. Re-open GoXLR Utility
1. 🩹 See the icon is present again in systray

---

Seems solvable quickly searching:

- https://stackoverflow.com/questions/32044732/how-to-restore-a-missing-notification-icon-when-explorer-exe-is-restarted

I'll look into submitting a PR myself if/when I have more time, but figured I'd simply report for now.

----

Now to report the same thing to Corsair for iCUE...

**Comment by FrostyCoolSlug** [comment]
*sobs quietly*

Looks like I'll need a bit of restructuring of the tray code, although shouldn't be too difficult, I'll try and get this fixed soon.

**Comment by FrostyCoolSlug** [comment]
This should be fixed now, can you give this test build a try please (check the artifacts at the bottom):

https://github.com/GoXLR-on-Linux/goxlr-utility/actions/runs/6075499743

**Comment by anthonybaldwin** [comment]
> This should be fixed now, can you give this test build a try please (check the artifacts at the bottom):
> 
> https://github.com/GoXLR-on-Linux/goxlr-utility/actions/runs/6075499743

Looks good to me. Thank you!
