### ISSUE TITLE
[Feature] Command-line ability for switching between profiles

### ISSUE THREAD

**Issue by Coldblackice** [GoXLR-on-Linux/goxlr-utility#125]
Would it be possible to add command-line ability, namely the ability to switch profiles via CLI?

This would open up the possibility of changing GoXLR profiles when switching to an OBS scene, e.g. switching to different mic profiles when changing to a new stream segment, game, media, or environment, etc. 

Perhaps a different mic profile is preferred when streaming in a different area (and thus acoustic layout) at a location, or adjusting EQ bands catered to a certain console or media, loosening gates, or even merely switching to a different color theme on the GoXLR itself according to stream segment (as a visual feedback/reminder while interviewing or live).

**Comment by FrostyCoolSlug** [comment]
This is already supported.

Check the `goxlr-client` binary in the utility's install directory, you can completely configure your GoXLR using it.

Thanks.
