### ISSUE TITLE
[Feature Request] GoXLR Mini channel volume always attached to fader

### ISSUE THREAD

**Issue by nenguard** [GoXLR-on-Linux/goxlr-utility#130]
Hello,

As a mini user, the fader and volume level will be unbound after the PC or app restart. I have to move the fader up and down to hook the volume to the fader, even if the fader and the actual volume level are in the same place.  After that, the fader can adjust the volume level. 

Due to this reason, it sometimes fails when I change the volume and stops me from subconsciously operation.

So is it possible to have the volume level always be based on the physical position of the fader? The possible solution I can think of is to have the app start up without loading any profile. Because when the app and the PC are closed, the fader still maintains control of the volume. But when the app starts (maybe because the profile is loaded), the fader is unbound from the volume.

Thanks

**Comment by JulanDeAlb** [comment]
Hey, sadly there is nothing we can do about. 
this needs to be done in the firmware of the device, which only TC-Helicon itself can do.
If you have heard about fader latching in either the official or our discord, this is what you are speaking about.

**Comment by FrostyCoolSlug** [comment]
I'm going to close this one as "can't fix", as @JulanDeAlb mentions, this is controlled by the firmware and not something we can do in software.
