### ISSUE TITLE
[Feature Reqest] Change fader channels with button press.

### ISSUE THREAD

**Issue by AquaCobell** [GoXLR-on-Linux/goxlr-utility#135]
Hi there, one thing about the goxlr which really annoyed me that there is no way to quickly change the fader setup.

Like right now i have mic, voicechat, music and system, lets say i play games i want to swap the system fader to game.

I could create different profiles and change them with the streamdeck however then all volume levels are different cause their saved within the profile. 

Would be cool if we could change the slider inputs on the fly.
Or maybe a setting to keep volume leves while changing profiles?

**Comment by JulanDeAlb** [comment]
Hey, what you are refering to is Fader Paging. This will not be implemented for the 1.X Version of the Utility since it would require a rewrite of the profile and break the compatiblilty with the official Software. It is however on the Roadmap for a 2.X Version

**Comment by FrostyCoolSlug** [comment]
Depending on usage, another option would be to use the Command Line client, in the installation directory there will be a `goxlr-client.exe` binary, you could run the following:

`goxlr-client.exe faders channel d game` - Which will put the 'Game' volume on Fader D (the last one)
`goxlr-client.exe faders channel d system` - Which will revert it back to the system fader

The main caveate with that is that if you have the 'System' channel muted when switching to 'Game', it'll unmute system, and vice versa. It also wont update the icon on the screen (you can use `goxlr-client.exe faders scribbles X <command>` to change those alongside other settings if needed.

**Comment by FrostyCoolSlug** [comment]
Closing, related is #88
