### ISSUE TITLE
Audio channels are combined to "GoXLR Multichannel"

### ISSUE THREAD

**Issue by Sporesirius** [GoXLR-on-Linux/goxlr-utility#138]
Hello,
I don't know how to describe the problem exactly, and I'm not sure where the problem is coming from.
I updated goxlr-utility from 0.12.6 to 1.0.0 and noticed that all sources and sinks like System, Mic Chat etc. were replaced with "GoXLR Multichannel". I tried a few things like reinstalling or downgrading, but it did not help. It is not a big problem that the channels are combined, but what is more problematic is that some applications, especially games running under wine, do not detect the source and sink, so I have no audio.

So maybe the problem is from my system, so I will also try another one, but maybe someone has an idea what the problem could be?

A few infos about my system:
```
OS: NixOS unstable
Kernel: 6.6.2
DE: Hyprland (Wayland)
```

```
✦ ❯ pipewire --version
pipewire
Compiled with libpipewire 0.3.84
Linked with libpipewire 0.3.84
```

```
✦ ❯ wpctl status
PipeWire 'pipewire-0' [0.3.84, jk@blackeye, cookie:4224853306]
 └─ Clients:
        33. .xdg-desktop-portal-hyprland-wrapped [0.3.84, jk@blackeye, pid:2596]
        34. WirePlumber                         [0.3.84, jk@blackeye, pid:2599]
        35. WirePlumber [export]                [0.3.84, jk@blackeye, pid:2599]
        74. wpctl                               [0.3.84, jk@blackeye, pid:134317]
        99. pipewire                            [0.3.84, jk@blackeye, pid:2808]
       100. WEBRTC VoiceEngine                  [0.3.84, jk@blackeye, pid:4357]
       102. WEBRTC VoiceEngine                  [0.3.84, jk@blackeye, pid:4357]
       104. spotify                             [0.3.84, jk@blackeye, pid:5858]
       106. Thunderbird                         [0.3.84, jk@blackeye, pid:5545]
       107. Firefox                             [0.3.84, jk@blackeye, pid:4731]
       108. Steam Voice Settings                [0.3.84, jk@blackeye, pid:7865]
       109. Steam                               [0.3.84, jk@blackeye, pid:7865]
       110. Chromium input                      [0.3.84, jk@blackeye, pid:4415]
       117. Firefox                             [0.3.84, jk@blackeye, pid:4731]

Audio
 ├─ Devices:
 │      45. HDA ATI HDMI                        [alsa]
 │      47. Camera                              [alsa]
 │      48. Rembrandt Radeon High Definition Audio Controller [alsa]
 │      49. Family 17h/19h HD Audio Controller  [alsa]
 │      94. GoXLR                               [alsa]
 │
 ├─ Sinks:
 │  *  129. GoXLR Multichannel                  [vol: 1.00]
 │
 ├─ Sink endpoints:
 │
 ├─ Sources:
 │  *  158. GoXLR Multichannel                  [vol: 1.00]
 │
 ├─ Source endpoints:
 │
 └─ Streams:
       101. Firefox
            103. output_FR       > GoXLR:playback_AUX1	[init]
            113. output_FL       > GoXLR:playback_AUX0	[init]
       112. Firefox
             28. output_FR       > GoXLR:playback_AUX1	[init]
            105. output_FL       > GoXLR:playback_AUX0	[init]
       119. spotify
            118. output_FL       > GoXLR:playback_AUX0	[active]
            122. output_FR       > GoXLR:playback_AUX1	[active]

....

Settings
 └─ Default Configured Node Names:
         0. Audio/Sink    alsa_output.usb-TC-Helicon_GoXLR-00.2.HiFi__goxlr_stereo_out_GoXLR_0_0_1__sink
         1. Audio/Source  alsa_input.usb-TC-Helicon_GoXLR-00.HiFi__goxlr_stereo_in_GoXLR_0_2_3__source
```

**Comment by FrostyCoolSlug** [comment]
Ok, can you open up `pavucontrol` (or equivalent) and check to make sure the GoXLR is using the default alsa profile, and not set to pro audio?

Thanks

**Comment by Sporesirius** [comment]
Yeah, GoXLR uses currently the Multichannel Duplex Profile, but there are also Multichannel Input, Multichannel Output and Pro Audio.

**Comment by FrostyCoolSlug** [comment]
1.2.10 introduced a bug which broke the GoXLR UCM Profile, a Fix has been made (available at https://github.com/alsa-project/alsa-ucm-conf/commit/b68aa52acdd2763fedad5eec0f435fbf43e5ccc6), but a release will need to happen to get that pulled in.

Could you look into manually updating the file? Not entirely sure how easy that'll be on Nix, but otherwise try downgrading `alsa-ucm-conf` back to 1.2.9

**Comment by FrostyCoolSlug** [comment]
For context, the profile in `pavucontrol` should look like this:

![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/574943/aa3ae673-b5f2-4378-b3ab-02013d080737)

But you'll likely need to fix `alsa-ucm-conf` to get that option.
