### ISSUE TITLE
GoXLR freezes and is no longer detected after waking from suspend

### ISSUE THREAD

**Issue by cpaczek** [GoXLR-on-Linux/goxlr-utility#139]
OS: Fedora 39
Repro steps:
systemctl suspend
wake from suspend using keyboard interupt
goxlr no longer works and is not detected

Fairly minor bug, only fix I could find is rebooting the pc.

**Comment by FrostyCoolSlug** [comment]
Does your GoXLR power off while your PC is suspended?

**Comment by FrostyCoolSlug** [comment]
Closing as stale.
