### ISSUE TITLE
[Feature] Command line options (CLI)

### ISSUE THREAD

**Issue by Coldblackice** [GoXLR-on-Linux/goxlr-utility#144]
I love this utility, especially all the improvements beyond the original it's received post open-sourcing! Thanks a lot for all your hard work put into this.

Would it be possible to add a basic command line interface? For switching profiles, and starting the utility on a particular profile.

It'd be phenomenally useful if this was possible, being able to quickly switch profiles and also start/automate the utility switching, such as via tasks.

**Comment by FrostyCoolSlug** [comment]
There's a `goxlr-client.exe` binary in the install directory of the utility :)

If you run it with `--help` it'll list all the commands / subcommands
