### ISSUE TITLE
Daemon freezing

### ISSUE THREAD

**Issue by ItMeCorban** [GoXLR-on-Linux/GoXLR-Utility#15]
GoXLR mini works okay with the regular script but when I try to run the daemon to use the utility, it works for a few seconds then cuts out. If I interrupt and launch the daemon again the faders start to work, but the daemon will report not being able to connect but eventually will. It then repeats the same behaviour, cutting out and becoming unresponsive until I relaunch the daemon.

I've attached the console output if that helps at all.

[Utility-output.txt](https://github.com/GoXLR-on-Linux/GoXLR-Utility/files/8654734/Utility-output.txt)

**Comment by FrostyCoolSlug** [comment]
Could you let me know what distro you're running on, as well as the firmware the GoXLR is currently using?

**Comment by FrostyCoolSlug** [comment]
While this was closed a while ago, the issue persisted. For anyone following, this was resolved in 4fdce88.
