### ISSUE TITLE
"Load Colour Profile" Bugged

### ISSUE THREAD

**Issue by red0x0002** [GoXLR-on-Linux/goxlr-utility#155]
Under System --> Power Actions --> "Load Colour Profile" 

This should be just loading the colour profile however it is loading the full profile and not just the colour. My sliders and everything reset to the default. It can be tested with following layout:

![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/93785137/5c526e92-caa2-4390-b1a6-3b7667985e68)

**Comment by FrostyCoolSlug** [comment]
Hi, could you please provide the `goxlr-daemon.log` file please? You can right click the tray, open path, logs to locate it.

**Comment by red0x0002** [comment]
[goxlr-daemon.log](https://github.com/GoXLR-on-Linux/goxlr-utility/files/14451056/goxlr-daemon.log)

**Comment by FrostyCoolSlug** [comment]
From what I can tell in the logs, Windows is always being shut down and isn't being put into sleep mode, so the sleep and wake actions are never being executed.

Shutting down Windows terminates the utility, meaning it has to restart on reboot, at which point it will fully load the previous profile as there's no way to track hardware state between restarts.
