### ISSUE TITLE
Physical Sliders not working anymore on Linux

### ISSUE THREAD

**Issue by N0m4n904** [GoXLR-on-Linux/goxlr-utility#157]
I just started my PC and tried to move the sliders, but they don't change the volume anymore.
I opened the web interface and tried setting the volume there and it works.

System:

Arch Linux
Linux Kernel 6.8.0
GoXLR Mini

![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/58194440/90e6ea66-31b4-48ae-9391-57209104e986)

**Comment by FrostyCoolSlug** [comment]
That's certainly unusual, if the webui can change the volume then the utility is working.. Does the lighting on the GoXLR reflect the changes made in the webui?

Can you try the following please, load a profile then move the physical faders to the top, then bottom, then top again bottom and see if they relatch, if that doesn't work try reassigning the faders in the UI.

I'm a little concerned about the reported FPGA, it should be 7, the fact it's not might imply a fault with the device, but I'm unsure.
