### ISSUE TITLE
build: current AUR package v1.0.6 seems to be broken

### ISSUE THREAD

**Issue by kedom1337** [GoXLR-on-Linux/goxlr-utility#158]
When trying to install the current version of `goxlr-utility` the installation fails with the following message:

```
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat '/goxlr-client.bash': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'goxlr-utility-1.0.6-1':
error: packages failed to build: goxlr-utility-1.0.6-1
```

This doesn't seem to be a local problem as I have personally reproduced it on two different machines. It has also been reported by a different user on the packages AUR page.

**Comment by FrostyCoolSlug** [comment]
Weird, I've just given it a test locally and from AUR and it seems to build and install correctly..

Could you try again and provide the full build log for me please?

**Comment by FrostyCoolSlug** [comment]
Found the problem, looks like a recent rust update has changed the JSON diagnostics, I suspect this will break a lot of rust packages in AUR, I'll look into getting a fix in.

**Comment by FrostyCoolSlug** [comment]
I've pushed a fix for this into AUR, should appear soon.

Thanks for reporting

**Comment by raccoroni** [comment]
fixed it for me, thank you boss :)

**Comment by kedom1337** [comment]
Yup everything works fine now. Thanks for the quick fix!
