### ISSUE TITLE
Interact with the IPC/Socket via NodeJS

### ISSUE THREAD

**Issue by DavidIlie** [GoXLR-on-Linux/goxlr-utility#16]
Very nice project!!

I have a somewhat unusual request... I would like to build my own desktop app using Electron and Websockets, and I want the server to be able to communicate with the daemon directly and see changes and send changes. Is that possible, and if so, where would I need to start? The preferred language would be Node.JS as I have experience building WebSockets unless there is an easy way to build a WebSocket server in rust (i have zero experience in rust haha).

Thanks!

**Comment by FrostyCoolSlug** [comment]
The IPC is rust serialised structures and objects, and will likely stay that way for a while. From a priority perspective replacing it with something else would be very time consuming while we have other tasks to work on.

**Comment by DavidIlie** [comment]
Good to know, thanks for the information!

**Comment by FrostyCoolSlug** [comment]
Just to update (in case you're still watching), we've moved our UI efforts to an embedded HTTP service, with the UI being built at https://github.com/GoXLR-on-Linux/goxlr-ui if you're still interested in contributing :)
