### ISSUE TITLE
GUI "Wrong" Frequencies Unit in Equaliser

### ISSUE THREAD

**Issue by Braastos** [GoXLR-on-Linux/goxlr-utility#167]
Just a really minor "issue" with the GUI on an GoXLR Mini with Utility Version 1.1.1 (not checked in earlier Versions)

If you open the advanced equaliser settings it displays only the first two frequencies corretly, the other are present as kHz, while being written as if the unit was Hz.
If you activate Fine Tune the displayed Unit will be Updated or the values are divided by 1000, so they are correct.

![Advanced Equaliser with "wrong" units](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/30237621/0e07a5b2-fb9e-458c-90c5-f6683030ac6c)

![Advanced Equaliser with Fine Tune enabled and "correct" units](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/30237621/e87972a4-7f0c-41d6-8726-714060faaf46)

**Comment by FrostyCoolSlug** [comment]
Thanks for the report, looks like I didn't properly test the mini when implementing the EQ bands, I'll try and get this fixed for the next release :)

**Comment by FrostyCoolSlug** [comment]
Ok, this is fixed in https://github.com/GoXLR-on-Linux/goxlr-ui/commit/30bca21c33fac836adb701600bc17f26bff50803 - scheduled for next release.
