### ISSUE TITLE
Icons under "Music" are not shown.

### ISSUE THREAD

**Issue by RileyMeta** [GoXLR-on-Linux/goxlr-utility#170]
This seems to be a fairly simple bug to reproduce, doesn't matter if it's the stand-alone app or in a browser. If you re-assign the the channels to use certain sources (as shown in the image with `system`) it fails to update the icon being used both in-browser and above the slider on the physical GoXLR.
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/32332593/d11f4a81-ba05-4c76-adc8-080b7f7ad2ad)

Fortunately, this is not a functionality issue, the slider(s) still work as intended, they're just mislabeled. 

Additional examples:
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/32332593/86b66f79-d929-4a76-9e99-122b9a21d3ac)
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/32332593/1f3d538f-a579-4129-9686-9860177708bf)
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/32332593/91a52c97-a0db-4d11-88b3-6aed2af061fc)
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/32332593/9520a85d-ae78-48a6-87d5-913de6c9144a)
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/32332593/94f93763-7ef5-4e6f-90ec-55d403f7125a)
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/32332593/31efafdc-19de-4f3a-a4e7-0df0adf4fad7)

And for some reason, if you set it to Line-out, it re-assigns the last slider to the "Music" icon.
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/32332593/edb6f2b7-2f30-4a29-b697-179db5a79b3f)

GoXLR Utility Info:
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/32332593/b494ef25-357e-4471-a29c-85003416bf6e)

**Comment by FrostyCoolSlug** [comment]
Ok, this is identical behaviour to the official app. The configuration of the icons that appear above the faders aren't connected to the actual assignment of the faders, it's just the defaults match the assignments. If you assign a channel to a fader that's already assigned to a different fader it will 'switch' the two channels, along with colours and the display.

If you go to Lighting -> Mixer, you can define the icon, and text displayed on the faders, both of which are free-form.
