### ISSUE TITLE
[Feature Request] Submixes

### ISSUE THREAD

**Issue by H-Duck** [GoXLR-on-Linux/goxlr-utility#180]
Around a month ago now the official GoXLR app got updated with submixes, and I was curious if this feature is intended to be released for the GoXLR Utility? I can't find details anywhere on the existing pages.

**Comment by FrostyCoolSlug** [comment]
So long as your GoXLR has the submix firmware installed, the utility already supports submixes.

To grab the firmware, you'll need to run the updates through the official app, once done you can startup the utility and the submix checkbox will be available.

Thanks.
