### ISSUE TITLE
Music and Chat faders swap!

### ISSUE THREAD

**Issue by Bizkep** [GoXLR-on-Linux/goxlr-utility#188]
For some reason my music and voice chat sliders are flip flop even when I save multiple times so they match on my GoXLR Mini! Kinda annoying.

**Comment by FrostyCoolSlug** [comment]
There's a known bug where if you swap two faders it doesn't save correctly, this is already fixed for 1.1.3.

In the meantime, you can work around it by using a different channel that isn't on a fader as an interim, so assign the music fader to line-out, then change the chat fader to music, and finish off by assigning the music fader to chat. This will then save correctly.

Thanks.

**Comment by FrostyCoolSlug** [comment]
Closing as fixed.
