### ISSUE TITLE
[Feature Request] Ability to map faders to non-GOXLR audio devices

### ISSUE THREAD

**Issue by darkscion0** [GoXLR-on-Linux/goxlr-utility#192]
For example, being able to setup a fader to control windows speaker volume. 

If not possible, it would be nice to be able to map a fader to control the volume of the built in Broadcast Stream Mix.

**Comment by FrostyCoolSlug** [comment]
This is out of the scope of the GoXLR Utility project. Physically changing faders directly modifies the mixing inside the physical device before it's presented to windows. There's no way to 'monitor' the values that wouldn't have unintended side effects inside the unit.
