### ISSUE TITLE
Spanish localization

### ISSUE THREAD

**Issue by ogomez92** [GoXLR-on-Linux/goxlr-utility#197]
Hello,
Are there plans for a Spanish localization? How do you get your localizations?

I'm up for translating, thank you!

I've used things like Poedit before, so if that's what you use I'm all in.

**Comment by parzival-space** [comment]
Hi,
You can create a pullrequest on the [goxlr-ui](https://github.com/GoXLR-on-Linux/goxlr-ui) repository as the project is currently not using any translation specific tools like Poedit.

Language files are stored as json files. You can copy one of these files and adjust them to your needs:  
https://github.com/GoXLR-on-Linux/goxlr-ui/tree/main/src/lang/languages  

To add a new languague all you have to do is this:
1. [Fork the repository](https://github.com/GoXLR-on-Linux/goxlr-ui/fork)  
2. Create your language file in [/src/lang/languages](https://github.com/GoXLR-on-Linux/goxlr-ui/tree/main/src/lang/languages)  
3. Add your new language to [config.js](https://github.com/GoXLR-on-Linux/goxlr-ui/blob/main/src/lang/config.js)  
4. [Create a Pull-Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by ogomez92** [comment]
Hi,
I forked the project and cloned it but there is no config.js and the src
folder doesn't  seem to be there.

Also all the json files seem to be in the rust's target directory.

Do I need to build it first?

Thanks.

**Comment by parzival-space** [comment]
You probably just forked the wrong reposity. You need to fork [GoXLR-on-Linux/goxlr-ui](https://github.com/GoXLR-on-Linux/goxlr-ui) and not [GoXLR-on-Linux/goxlr-utility](https://github.com/GoXLR-on-Linux/goxlr-utility/).

**Comment by ogomez92** [comment]
Haha... Obviously that was it, I didn't know there were two repositories...
Thanks.

**Comment by ogomez92** [comment]
Hi,
Can I translate the channel names? I'm confused as whether these can be
translated or not, since I don't think the GoXLR has a Spanish driver and
thus the mapping might fail?

// For these, the keys map directly to their GoXLR Channel Names

Game, Microphone, etc.

Thanks!

**Comment by FrostyCoolSlug** [comment]
Don't translate them for now, I'm likely going to be removing the channel name translations in the future for this reason, they should match the names in Windows.

**Comment by FrostyCoolSlug** [comment]
Thanks for the contribution, I've merged spanish into the Utility UI project.

Are you happy to close this one?

**Comment by ogomez92** [comment]
Hi, actually I had a question before closing.. the tts strings are not included in the other repo, because they are generated by this Rust project I guess.

I am referring to thigns like effectname 25%, stream muted, microphone unmuted...

I understand there's nom lang project on this one and it might requrie a bit more work, it's not essential, I can close this one if it's too much work as I don't have the capacity to work on this at the moment as I don't know this project very well and I'm a bit limited with Rust.

Any ideas?

Thanks.

**Comment by ogomez92** [comment]
Ah I just saw the comment in the other repo, sorry for opening it here, I didn't know there were two repos.

Closing this. Thanks again.
