### ISSUE TITLE
Unable to locate GoXLR Audio Script, sampler disabled

### ISSUE THREAD

**Issue by joaoescribano** [GoXLR-on-Linux/goxlr-utility#25]
Hello, first of all, thank you so much! I tried the goxlr-on-linux but no success, and now... it's almost perfect!

I just got 2 issues to solve:

1) The title of this issue, when i try  to run the daemon i get this message:
```bash
escribano@escribano:/usr/bin$ goxlr-daemon 
22:21:20 [INFO] Starting 12 workers
22:21:20 [INFO] Started GoXLR configuration interface at http://127.0.0.1:14564/
22:21:20 [INFO] Tokio runtime found; starting in existing Tokio runtime
22:21:20 [INFO] Connected to possible GoXLR device at Bus 003 Device 010: ID 1220:8fe0
22:21:20 [INFO] Configuring GoXLR, Profile: Default, Mic Profile: Default
Unhandled Tag: animationTree
22:21:20 [ERROR] Unable to locate GoXLR Audio Script, Sampler Disabled.
```

I didn't find any reference to this audio script, I really dunno what this is.

2) I don't see the audio channels so I can change the OS to properly map the input/output to the desired port.
The only port I found in my system is "Multichannel Output - GoXLR" which simply doesn't work at all.

I'm missing something? Thanks

**Comment by FrostyCoolSlug** [comment]
Hi, can you let me know what distro you're using please?

The util doesn't support the sampler yet, so that error can be ignored (I'll hide it in future releases until it's finished).

I updated the readme last night noting that audio setup needs to be handled separately from the utility, for distributions running older packages you may need to use the [GoXLR on Linux](https://github.com/GoXLR-on-Linux/goxlr-on-linux) setup script to sort your audio.

**Comment by joaoescribano** [comment]
Got it! so I'll ignore it!

Here is the info you asked:
```bash
escribano@escribano:~$ uname -a
Linux escribano 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by joaoescribano** [comment]
I'll also check the readme and try to use the setup script from the other repo.
Can't wait to make it work so i can try to help too!

Thanks!

**Comment by joaoescribano** [comment]
@FrostyCoolSlug it worked!

After uninstalling everything and running the script from scratch, it installed everything well and it worked!

Thanks a lot!
