### ISSUE TITLE
GOXLR-Mini does not work

### ISSUE THREAD

**Issue by GabrielZacarias** [GoXLR-on-Linux/goxlr-utility#29]
The goxlr-mini isn't working at all, the app won't pick it up and / or the daemon can't initialise it.

This issue is due to the system agent that initialises as root the goxlr when plugged in. As the agent looks for a device with the device ID of a full GoXlr, it doesn't pick up the mini.

・Fix :
You can edit the file:

`/Library/LaunchAgents/com.adesky.goxlr.plist`

and change the id as below:

```
<key>idProduct</key>
<integer>36836</integer>
```

then do in Terminal:

```
launchctl unload /Library/LaunchAgents/com.adesky.goxlr.plist
launchctl load /Library/LaunchAgents/com.adesky.goxlr.plist
```

**Comment by Adelenade** [comment]
Hmmmm, I think it's an error, first it's on the wrong repo (this repository is for the GoXlr-utility and not for the goxlr-on-macos project), and it's a known issue, literally copy / pasted from the known issue post that I just did in the discord server <_>

So as it's a known issue, and on files not added by the goxlr-utility, no need to open an github issue ! :3 (as even on my own repository it's obviously going to be fixed)

**Comment by GabrielZacarias** [comment]
@Adelenade apologies, wrong repo
