### ISSUE TITLE
Request - Scrolling on the volume sliders in the UI should adjust their volume

### ISSUE THREAD

**Issue by ItMeCorban** [GoXLR-on-Linux/goxlr-utility#33]
Same as you could on a tray icon or brightness slider

**Comment by FrostyCoolSlug** [comment]
To clarify, are you referring to using the mouse scroll wheel on the sliders?

**Comment by ItMeCorban** [comment]
Yea, when hovering over in the web ui, I sometimes use the PC to play media on the TV so being able to quickly adjust the volume go xlr volume that way would be handy

**Comment by FrostyCoolSlug** [comment]
Ok, thanks.

Could you reopen this on the [GoXLR UI Project](https://github.com/goxlr-on-Linux/goxlr-ui/), Just so it's handled there?

Thanks.

**Comment by ItMeCorban** [comment]
oops yep didn't see that will do
