### ISSUE TITLE
No access to your Discord server

### ISSUE THREAD

**Issue by DJkefo** [GoXLR-on-Linux/goxlr-utility#43]
Your Discord Link doesn't work, I want to ask for help there because it's too stupid for github. 

To keep it short, I want to use your app on shutdown on my pc to switch the GoXLR to sleep mode on shutdown, but it doesn't work since the configs are stored in AppData. Win user btw

**Comment by Ginjah6205** [comment]
Discord Link here: https://discord.gg/JPFjHecV

**Comment by DJkefo** [comment]
> I've just run around testing all the discord links, and they do seem to work, the 'official' link is https://discord.gg/Wbp3UxkX2j (no expiry) although it's always possible discord was having some kind of problem (thanks @Ginjah6205 for the extra link!).

Somehow the link still doesn't work but well I can try some things, maybe it's just me being an idiot

> 
> The utility is intended on being a complete replacement for the official Windows App, rather than a suppliment (the two apps will conflict against each other), so can't really be used to perform a specific action on shutdown without having it running during normal use.

I know that it's supposed to be a replacement, but the goxlr app (obviously) wouldn't work during shutdown, because it requires to load the UI I think. What I was trying to do was to put a batch file in the shutdown directory in the group policy editor and it would work if the config files weren't located in my appdata folder, since in the shutdown script logs me out on shutdown and then runs the batch file as the SYSTEM account instead of my personal account (which also doesn't seem to have an AppData folder, which in the end just does nothing). Is it possible to move the config files from AppData to a publicly accessible folder on the system?
Since I'm logging out it also closes the official GoXLR App and I planned then to open up this GoXLR Toolkit once I'm logged out with the default profile loaded as Sleep to turn the lights of the GoXLR off on shutdown. 
> 
> Executing commands on the utilities shutdown is something that's been worked into 0.10.0 (including detection of Windows shutdown), but currently isn't in a massively usable state, nor properly tested / released yet. When 0.10.0 comes around, the situation should be better.
