### ISSUE TITLE
Noise Threshold for triggering Recording a Sample at Beginning is too low

### ISSUE THREAD

**Issue by hllf** [GoXLR-on-Linux/goxlr-utility#44]
The daemon is correctly now trying to ignore silence at the start of a sample recording, as the main GoXLR app on Windows does. However, the threshold is too low. If you are not speaking and have very little background noise, it is recording, and it should not. It should only record if there is more noise. I have a Shure SM7B, which passes through very little background sound, and unless I mute it, the daemon records the sample.

I tested against the Windows main GoXLR app, and it doesn't start recording until a much higher noise threshhold.

If this can be raised, that would be great. I don't have the exact DB where this should happen, but I'm thinking maybe -45 to -40.

**Comment by FrostyCoolSlug** [comment]
I'll get this changed, I set it to -80 while testing, assuming things like the gate would be in effect, but as you say there are cases where that may not be in use so it'll still record everything. -45 seems like a reasonable middle ground for it

**Comment by FrostyCoolSlug** [comment]
I've tweaked this to -45 in 7e6f32a, could you give it a test and see if it's better?

**Comment by hllf** [comment]
Yes it's much better; based on my initial testing, it's pretty much perfect now. I'll comment if I see anything different with more testing.

**Comment by hllf** [comment]
I think this issue can be closed; I've found -45 to be a good value.
