### ISSUE TITLE
Line Out don't work

### ISSUE THREAD

**Issue by TechnoLulWxD** [GoXLR-on-Linux/goxlr-utility#46]
Line out wont work no matter what im doing. In windows it works perfectly fine, in linux it doesnt.

**Comment by FrostyCoolSlug** [comment]
Can you please provide the output of `goxlr-client --status-json`?

**Comment by TechnoLulWxD** [comment]
`{
  "config": {
    "daemon_version": "0.9.0",
    "autostart_enabled": true,
    "show_tray_icon": true
  },
  "mixers": {
    "S200804824CQK": {
      "hardware": {
        "versions": {
          "firmware": [
            1,
            3,
            44,
            105
          ],
          "fpga_count": 7,
          "dice": [
            1,
            3,
            9,
            100
          ]
        },
        "serial_number": "S200804824CQK",
        "manufactured_date": "2020-08-21",
        "device_type": "Full",
        "usb_device": {
          "manufacturer_name": "TC-Helicon",
          "product_name": "GoXLR",
          "version": [
            2,
            0,
            0
          ],
          "bus_number": 1,
          "address": 7,
          "identifier": null
        }
      },
      "fader_status": {
        "A": {
          "channel": "System",
          "mute_type": "All",
          "scribble": {
            "file_name": "level.png",
            "bottom_text": null,
            "left_text": null,
            "inverted": false
          },
          "mute_state": "Unmuted"
        },
        "B": {
          "channel": "Chat",
          "mute_type": "All",
          "scribble": {
            "file_name": "person.png",
            "bottom_text": null,
            "left_text": null,
            "inverted": false
          },
          "mute_state": "Unmuted"
        },
        "C": {
          "channel": "Music",
          "mute_type": "All",
          "scribble": {
            "file_name": "music.png",
            "bottom_text": null,
            "left_text": null,
            "inverted": false
          },
          "mute_state": "Unmuted"
        },
        "D": {
          "channel": "Game",
          "mute_type": "All",
          "scribble": {
            "file_name": "headphone.png",
            "bottom_text": null,
            "left_text": null,
            "inverted": false
          },
          "mute_state": "Unmuted"
        }
      },
      "mic_status": {
        "mic_type": "Dynamic",
        "mic_gains": {
          "Dynamic": 60,
          "Condenser": 30,
          "Jack": 30
        },
        "equaliser": {
          "gain": {
            "Equalizer250Hz": -3,
            "Equalizer1KHz": -1,
            "Equalizer63Hz": -3,
            "Equalizer8KHz": -1,
            "Equalizer125Hz": -3,
            "Equalizer2KHz": -1,
            "Equalizer4KHz": -1,
            "Equalizer31Hz": -3,
            "Equalizer500Hz": -1,
            "Equalizer16KHz": -1
          },
          "frequency": {
            "Equalizer31Hz": 31.5,
            "Equalizer500Hz": 500.0,
            "Equalizer63Hz": 63.0,
            "Equalizer16KHz": 16000.0,
            "Equalizer1KHz": 1000.0,
            "Equalizer2KHz": 2000.0,
            "Equalizer250Hz": 250.0,
            "Equalizer4KHz": 4000.0,
            "Equalizer125Hz": 125.0,
            "Equalizer8KHz": 8000.0
          }
        },
        "equaliser_mini": {
          "gain": {
            "Equalizer3KHz": -1,
            "Equalizer500Hz": -1,
            "Equalizer90Hz": -3,
            "Equalizer1KHz": -1,
            "Equalizer8KHz": -1,
            "Equalizer250Hz": -3
          },
          "frequency": {
            "Equalizer3KHz": 4500.0,
            "Equalizer250Hz": 160.0,
            "Equalizer90Hz": 90.0,
            "Equalizer1KHz": 1500.0,
            "Equalizer500Hz": 480.0,
            "Equalizer8KHz": 7800.0
          }
        },
        "noise_gate": {
          "threshold": -40,
          "attack": 0,
          "release": 19,
          "enabled": true,
          "attenuation": 100
        },
        "compressor": {
          "threshold": -12,
          "ratio": 9,
          "attack": 1,
          "release": 9,
          "makeup_gain": 3
        }
      },
      "levels": {
        "volumes": {
          "Mic": 255,
          "LineIn": 128,
          "Console": 128,
          "System": 138,
          "Game": 153,
          "Chat": 150,
          "Sample": 255,
          "Music": 142,
          "Headphones": 255,
          "MicMonitor": 128,
          "LineOut": 255
        },
        "bleep": -20,
        "deess": 100
      },
      "router": {
        "Microphone": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": false,
          "ChatMic": true,
          "Sampler": true
        },
        "Chat": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "Music": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "Game": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "Console": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "LineIn": {
          "Headphones": false,
          "BroadcastMix": false,
          "LineOut": false,
          "ChatMic": false,
          "Sampler": false
        },
        "System": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "Samples": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": false,
          "ChatMic": true,
          "Sampler": false
        }
      },
      "cough_button": {
        "is_toggle": true,
        "mute_type": "ToVoiceChat",
        "state": "Unmuted"
      },
      "lighting": {
        "faders": {
          "B": {
            "style": "Gradient",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "A": {
            "style": "Gradient",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "D": {
            "style": "Gradient",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "C": {
            "style": "Gradient",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          }
        },
        "buttons": {
          "Fader4Mute": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "EffectRobot": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectMegaphone": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Bleep": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect1": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect3": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Cough": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect2": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect6": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Fader2Mute": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "EffectHardTune": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect4": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectFx": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Fader3Mute": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "EffectSelect5": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Fader1Mute": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          }
        },
        "simple": {
          "Global": {
            "colour_one": "003FFA"
          },
          "Accent": {
            "colour_one": "FF00C8"
          },
          "Scribble4": {
            "colour_one": "00FFFF"
          },
          "Scribble3": {
            "colour_one": "00FFFF"
          },
          "Scribble2": {
            "colour_one": "00FFFF"
          },
          "Scribble1": {
            "colour_one": "00FFFF"
          }
        },
        "sampler": {
          "SamplerSelectB": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF",
              "colour_three": "000000"
            }
          },
          "SamplerSelectC": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF",
              "colour_three": "000000"
            }
          },
          "SamplerSelectA": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF",
              "colour_three": "000000"
            }
          }
        },
        "encoders": {
          "Echo": {
            "colour_one": "000000",
            "colour_two": "FF00C8",
            "colour_three": "00FFFF"
          },
          "Reverb": {
            "colour_one": "000000",
            "colour_two": "FF00C8",
            "colour_three": "00FFFF"
          },
          "Pitch": {
            "colour_one": "000000",
            "colour_two": "FF00C8",
            "colour_three": "00FFFF"
          },
          "Gender": {
            "colour_one": "000000",
            "colour_two": "FF00C8",
            "colour_three": "00FFFF"
          }
        }
      },
      "effects": {
        "is_enabled": false,
        "active_preset": "Preset2",
        "preset_names": {
          "Preset2": "Big Verb",
          "Preset4": "HardTune Music",
          "Preset6": "Tank",
          "Preset3": "Comms Radio",
          "Preset5": "Kid Robot",
          "Preset1": "Big Echo"
        },
        "current": {
          "reverb": {
            "style": "HockeyArena",
            "amount": 62,
            "decay": 6000,
            "early_level": 0,
            "tail_level": -2,
            "pre_delay": 100,
            "lo_colour": 10,
            "hi_colour": -39,
            "hi_factor": 21,
            "diffuse": 0,
            "mod_speed": -3,
            "mod_depth": 21
          },
          "echo": {
            "style": "Quarter",
            "amount": 0,
            "feedback": 30,
            "tempo": 149,
            "delay_left": 500,
            "delay_right": 500,
            "feedback_left": 50,
            "feedback_right": 50,
            "feedback_xfb_l_to_r": 0,
            "feedback_xfb_r_to_l": 0
          },
          "pitch": {
            "style": "Narrow",
            "amount": 0,
            "character": 100
          },
          "gender": {
            "style": "Narrow",
            "amount": 0
          },
          "megaphone": {
            "is_enabled": false,
            "style": "Megaphone",
            "amount": 0,
            "post_gain": 2
          },
          "robot": {
            "is_enabled": false,
            "style": "Robot1",
            "low_gain": -10,
            "low_freq": 88,
            "low_width": 0,
            "mid_gain": 5,
            "mid_freq": 173,
            "mid_width": 25,
            "high_gain": 0,
            "high_freq": 182,
            "high_width": 0,
            "waveform": 0,
            "pulse_width": 50,
            "threshold": -36,
            "dry_mix": -6
          },
          "hard_tune": {
            "is_enabled": false,
            "style": "Natural",
            "amount": 70,
            "rate": 20,
            "window": 20,
            "source": "All"
          }
        }
      },
      "sampler": {
        "banks": {
          "A": {
            "TopRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "BottomRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "TopLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [
                {
                  "name": "Recording_2022-09-06T075929.wav",
                  "start_pct": 0.0,
                  "stop_pct": 100.0
                }
              ],
              "is_playing": false
            },
            "BottomLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            }
          },
          "B": {
            "BottomLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "BottomRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "TopRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "TopLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            }
          },
          "C": {
            "TopLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "BottomRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "TopRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "BottomLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            }
          }
        }
      },
      "settings": {
        "display": {
          "gate": "Advanced",
          "compressor": "Simple",
          "equaliser": "Simple",
          "equaliser_fine": "Simple"
        },
        "mute_hold_duration": 500,
        "vc_mute_also_mute_cm": true
      },
      "button_down": {
        "Fader1Mute": false,
        "Fader2Mute": false,
        "Fader3Mute": false,
        "Fader4Mute": false,
        "Bleep": false,
        "Cough": false,
        "EffectSelect1": false,
        "EffectSelect2": false,
        "EffectSelect3": false,
        "EffectSelect4": false,
        "EffectSelect5": false,
        "EffectSelect6": false,
        "EffectFx": false,
        "EffectMegaphone": false,
        "EffectRobot": false,
        "EffectHardTune": false,
        "SamplerSelectA": false,
        "SamplerSelectB": false,
        "SamplerSelectC": false,
        "SamplerTopLeft": false,
        "SamplerTopRight": false,
        "SamplerBottomLeft": false,
        "SamplerBottomRight": false,
        "SamplerClear": false
      },
      "profile_name": "Default - No Display",
      "mic_profile_name": "hehe"
    }
  },
  "paths": {
    "profile_directory": "/home/ubuntu/.local/share/goxlr-utility/profiles",
    "mic_profile_directory": "/home/ubuntu/.local/share/goxlr-utility/mic-profiles",
    "samples_directory": "/home/ubuntu/.local/share/goxlr-utility/samples",
    "presets_directory": "/home/ubuntu/.local/share/goxlr-utility/presets",
    "icons_directory": "/home/ubuntu/.local/share/goxlr-utility/icons"
  },
  "files": {
    "profiles": [
      "Default",
      "Default - Display",
      "Default - No Display",
      "Default - Red",
      "Default - Teal Blue",
      "Default - Vaporwave",
      "Sleep"
    ],
    "mic_profiles": [
      "DEFAULT",
      "DEFAULT (2)",
      "DEFAULT - Copy",
      "hehe"
    ],
    "presets": [
      "Big Echo",
      "Big Verb",
      "Comms Radio",
      "HardTune Music",
      "Kid Robot",
      "PitchDn Echo",
      "Tank"
    ],
    "samples": {},
    "icons": [
      "headphone.png",
      "level.png",
      "lightbulb2.png",
      "mic.png",
      "mic3.png",
      "music.png",
      "person.png",
      "scale.png"
    ]
  }
}`

**Comment by TechnoLulWxD** [comment]
{
  "config": {
    "daemon_version": "0.9.0",
    "autostart_enabled": true,
    "show_tray_icon": true
  },
  "mixers": {
    "S200804824CQK": {
      "hardware": {
        "versions": {
          "firmware": [
            1,
            3,
            44,
            105
          ],
          "fpga_count": 7,
          "dice": [
            1,
            3,
            9,
            100
          ]
        },
        "serial_number": "S200804824CQK",
        "manufactured_date": "2020-08-21",
        "device_type": "Full",
        "usb_device": {
          "manufacturer_name": "TC-Helicon",
          "product_name": "GoXLR",
          "version": [
            2,
            0,
            0
          ],
          "bus_number": 1,
          "address": 7,
          "identifier": null
        }
      },
      "fader_status": {
        "A": {
          "channel": "System",
          "mute_type": "All",
          "scribble": {
            "file_name": "level.png",
            "bottom_text": null,
            "left_text": null,
            "inverted": false
          },
          "mute_state": "Unmuted"
        },
        "B": {
          "channel": "Chat",
          "mute_type": "All",
          "scribble": {
            "file_name": "person.png",
            "bottom_text": null,
            "left_text": null,
            "inverted": false
          },
          "mute_state": "Unmuted"
        },
        "C": {
          "channel": "Music",
          "mute_type": "All",
          "scribble": {
            "file_name": "music.png",
            "bottom_text": null,
            "left_text": null,
            "inverted": false
          },
          "mute_state": "Unmuted"
        },
        "D": {
          "channel": "Game",
          "mute_type": "All",
          "scribble": {
            "file_name": "headphone.png",
            "bottom_text": null,
            "left_text": null,
            "inverted": false
          },
          "mute_state": "Unmuted"
        }
      },
      "mic_status": {
        "mic_type": "Dynamic",
        "mic_gains": {
          "Dynamic": 60,
          "Condenser": 30,
          "Jack": 30
        },
        "equaliser": {
          "gain": {
            "Equalizer250Hz": -3,
            "Equalizer1KHz": -1,
            "Equalizer63Hz": -3,
            "Equalizer8KHz": -1,
            "Equalizer125Hz": -3,
            "Equalizer2KHz": -1,
            "Equalizer4KHz": -1,
            "Equalizer31Hz": -3,
            "Equalizer500Hz": -1,
            "Equalizer16KHz": -1
          },
          "frequency": {
            "Equalizer31Hz": 31.5,
            "Equalizer500Hz": 500.0,
            "Equalizer63Hz": 63.0,
            "Equalizer16KHz": 16000.0,
            "Equalizer1KHz": 1000.0,
            "Equalizer2KHz": 2000.0,
            "Equalizer250Hz": 250.0,
            "Equalizer4KHz": 4000.0,
            "Equalizer125Hz": 125.0,
            "Equalizer8KHz": 8000.0
          }
        },
        "equaliser_mini": {
          "gain": {
            "Equalizer3KHz": -1,
            "Equalizer500Hz": -1,
            "Equalizer90Hz": -3,
            "Equalizer1KHz": -1,
            "Equalizer8KHz": -1,
            "Equalizer250Hz": -3
          },
          "frequency": {
            "Equalizer3KHz": 4500.0,
            "Equalizer250Hz": 160.0,
            "Equalizer90Hz": 90.0,
            "Equalizer1KHz": 1500.0,
            "Equalizer500Hz": 480.0,
            "Equalizer8KHz": 7800.0
          }
        },
        "noise_gate": {
          "threshold": -40,
          "attack": 0,
          "release": 19,
          "enabled": true,
          "attenuation": 100
        },
        "compressor": {
          "threshold": -12,
          "ratio": 9,
          "attack": 1,
          "release": 9,
          "makeup_gain": 3
        }
      },
      "levels": {
        "volumes": {
          "Mic": 255,
          "LineIn": 128,
          "Console": 128,
          "System": 138,
          "Game": 153,
          "Chat": 150,
          "Sample": 255,
          "Music": 142,
          "Headphones": 255,
          "MicMonitor": 128,
          "LineOut": 255
        },
        "bleep": -20,
        "deess": 100
      },
      "router": {
        "Microphone": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": false,
          "ChatMic": true,
          "Sampler": true
        },
        "Chat": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "Music": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "Game": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "Console": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "LineIn": {
          "Headphones": false,
          "BroadcastMix": false,
          "LineOut": false,
          "ChatMic": false,
          "Sampler": false
        },
        "System": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": true,
          "ChatMic": false,
          "Sampler": false
        },
        "Samples": {
          "Headphones": true,
          "BroadcastMix": false,
          "LineOut": false,
          "ChatMic": true,
          "Sampler": false
        }
      },
      "cough_button": {
        "is_toggle": true,
        "mute_type": "ToVoiceChat",
        "state": "Unmuted"
      },
      "lighting": {
        "faders": {
          "B": {
            "style": "Gradient",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "A": {
            "style": "Gradient",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "D": {
            "style": "Gradient",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "C": {
            "style": "Gradient",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          }
        },
        "buttons": {
          "Fader4Mute": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "EffectRobot": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectMegaphone": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Bleep": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect1": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect3": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Cough": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect2": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect6": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Fader2Mute": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "EffectHardTune": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectSelect4": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "EffectFx": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Fader3Mute": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          },
          "EffectSelect5": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF"
            }
          },
          "Fader1Mute": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "00FFFF",
              "colour_two": "FF00C8"
            }
          }
        },
        "simple": {
          "Global": {
            "colour_one": "003FFA"
          },
          "Accent": {
            "colour_one": "FF00C8"
          },
          "Scribble4": {
            "colour_one": "00FFFF"
          },
          "Scribble3": {
            "colour_one": "00FFFF"
          },
          "Scribble2": {
            "colour_one": "00FFFF"
          },
          "Scribble1": {
            "colour_one": "00FFFF"
          }
        },
        "sampler": {
          "SamplerSelectB": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF",
              "colour_three": "000000"
            }
          },
          "SamplerSelectC": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF",
              "colour_three": "000000"
            }
          },
          "SamplerSelectA": {
            "off_style": "Colour2",
            "colours": {
              "colour_one": "FF00C8",
              "colour_two": "00FFFF",
              "colour_three": "000000"
            }
          }
        },
        "encoders": {
          "Echo": {
            "colour_one": "000000",
            "colour_two": "FF00C8",
            "colour_three": "00FFFF"
          },
          "Reverb": {
            "colour_one": "000000",
            "colour_two": "FF00C8",
            "colour_three": "00FFFF"
          },
          "Pitch": {
            "colour_one": "000000",
            "colour_two": "FF00C8",
            "colour_three": "00FFFF"
          },
          "Gender": {
            "colour_one": "000000",
            "colour_two": "FF00C8",
            "colour_three": "00FFFF"
          }
        }
      },
      "effects": {
        "is_enabled": false,
        "active_preset": "Preset2",
        "preset_names": {
          "Preset2": "Big Verb",
          "Preset4": "HardTune Music",
          "Preset6": "Tank",
          "Preset3": "Comms Radio",
          "Preset5": "Kid Robot",
          "Preset1": "Big Echo"
        },
        "current": {
          "reverb": {
            "style": "HockeyArena",
            "amount": 62,
            "decay": 6000,
            "early_level": 0,
            "tail_level": -2,
            "pre_delay": 100,
            "lo_colour": 10,
            "hi_colour": -39,
            "hi_factor": 21,
            "diffuse": 0,
            "mod_speed": -3,
            "mod_depth": 21
          },
          "echo": {
            "style": "Quarter",
            "amount": 0,
            "feedback": 30,
            "tempo": 149,
            "delay_left": 500,
            "delay_right": 500,
            "feedback_left": 50,
            "feedback_right": 50,
            "feedback_xfb_l_to_r": 0,
            "feedback_xfb_r_to_l": 0
          },
          "pitch": {
            "style": "Narrow",
            "amount": 0,
            "character": 100
          },
          "gender": {
            "style": "Narrow",
            "amount": 0
          },
          "megaphone": {
            "is_enabled": false,
            "style": "Megaphone",
            "amount": 0,
            "post_gain": 2
          },
          "robot": {
            "is_enabled": false,
            "style": "Robot1",
            "low_gain": -10,
            "low_freq": 88,
            "low_width": 0,
            "mid_gain": 5,
            "mid_freq": 173,
            "mid_width": 25,
            "high_gain": 0,
            "high_freq": 182,
            "high_width": 0,
            "waveform": 0,
            "pulse_width": 50,
            "threshold": -36,
            "dry_mix": -6
          },
          "hard_tune": {
            "is_enabled": false,
            "style": "Natural",
            "amount": 70,
            "rate": 20,
            "window": 20,
            "source": "All"
          }
        }
      },
      "sampler": {
        "banks": {
          "A": {
            "TopRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "BottomRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "TopLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [
                {
                  "name": "Recording_2022-09-06T075929.wav",
                  "start_pct": 0.0,
                  "stop_pct": 100.0
                }
              ],
              "is_playing": false
            },
            "BottomLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            }
          },
          "B": {
            "BottomLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "BottomRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "TopRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "TopLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            }
          },
          "C": {
            "TopLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "BottomRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "TopRight": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            },
            "BottomLeft": {
              "function": "PlayNext",
              "order": "Sequential",
              "samples": [],
              "is_playing": false
            }
          }
        }
      },
      "settings": {
        "display": {
          "gate": "Advanced",
          "compressor": "Simple",
          "equaliser": "Simple",
          "equaliser_fine": "Simple"
        },
        "mute_hold_duration": 500,
        "vc_mute_also_mute_cm": true
      },
      "button_down": {
        "Fader1Mute": false,
        "Fader2Mute": false,
        "Fader3Mute": false,
        "Fader4Mute": false,
        "Bleep": false,
        "Cough": false,
        "EffectSelect1": false,
        "EffectSelect2": false,
        "EffectSelect3": false,
        "EffectSelect4": false,
        "EffectSelect5": false,
        "EffectSelect6": false,
        "EffectFx": false,
        "EffectMegaphone": false,
        "EffectRobot": false,
        "EffectHardTune": false,
        "SamplerSelectA": false,
        "SamplerSelectB": false,
        "SamplerSelectC": false,
        "SamplerTopLeft": false,
        "SamplerTopRight": false,
        "SamplerBottomLeft": false,
        "SamplerBottomRight": false,
        "SamplerClear": false
      },
      "profile_name": "Default - No Display",
      "mic_profile_name": "hehe"
    }
  },
  "paths": {
    "profile_directory": "/home/ubuntu/.local/share/goxlr-utility/profiles",
    "mic_profile_directory": "/home/ubuntu/.local/share/goxlr-utility/mic-profiles",
    "samples_directory": "/home/ubuntu/.local/share/goxlr-utility/samples",
    "presets_directory": "/home/ubuntu/.local/share/goxlr-utility/presets",
    "icons_directory": "/home/ubuntu/.local/share/goxlr-utility/icons"
  },
  "files": {
    "profiles": [
      "Default",
      "Default - Display",
      "Default - No Display",
      "Default - Red",
      "Default - Teal Blue",
      "Default - Vaporwave",
      "Sleep"
    ],
    "mic_profiles": [
      "DEFAULT",
      "DEFAULT (2)",
      "DEFAULT - Copy",
      "hehe"
    ],
    "presets": [
      "Big Echo",
      "Big Verb",
      "Comms Radio",
      "HardTune Music",
      "Kid Robot",
      "PitchDn Echo",
      "Tank"
    ],
    "samples": {},
    "icons": [
      "headphone.png",
      "level.png",
      "lightbulb2.png",
      "mic.png",
      "mic3.png",
      "music.png",
      "person.png",
      "scale.png"
    ]
  }
}

**Comment by FrostyCoolSlug** [comment]
Everything looks configured ok, can you plug your headphones into your line-out port and check for audio (if you haven't already), and if that's doesn't work, attach your profile so I can try to recreate the issue.

Thanks

**Comment by TechnoLulWxD** [comment]
Headset also didnt work on line-out. When I boot into Windows everything works fine and the profile is the same as i used in windows before.
[Default - No Display.zip](https://github.com/GoXLR-on-Linux/goxlr-utility/files/10771665/Default.-.No.Display.zip)

**Comment by FrostyCoolSlug** [comment]
Unfortunately, I'm not able to reproduce this issue. Your config looks fine, you're running the same firmware as I am, but loading your profile results in correct line-out behaviour on the GoXLR. 

This is going to be difficult to track down without reproduction, all I can suggest for now, is to double check your cables are plugged into the correct ports, and try changing the line-out volume manually in the UI in case it's not being correctly set on profile load.

Thanks.

**Comment by TechnoLulWxD** [comment]
I will check everything again and try to figure out what cause the problem. But thanks for your time
