### ISSUE TITLE
Couldn't load mic profile DEFAULT

### ISSUE THREAD

**Issue by g123k** [GoXLR-on-Linux/goxlr-utility#54]
Hi everyone,

I'm on macOS and I've successfuly compiled all binaries.
When done, I've `goxlr-initializer`, which seems OK:

```
Checking for available GoXLR devices..
Found GoXLR Device (bus 6, port 1, device 16), checking state..
Device (bus 6, port 1, device 16) already initialised
```

However, the daemon fails with:

```
13:12:07 [INFO] Starting GoXLR Daemon v0.10.0
13:12:07 [INFO] Performing Platform Preflight...
13:12:07 [INFO] Bound IPC Socket @ /tmp/goxlr.socket
13:12:07 [INFO] Started GoXLR configuration interface at http://localhost:14564/
13:12:07 [INFO] Connected to possible GoXLR device at Bus 006 Device 016: ID 1220:8fe0
13:12:07 [INFO] Configuring GoXLR, Profile: DEFAULT, Mic Profile: DEFAULT
13:12:07 [WARN] Error Loading Profile, falling back to default.. Profile DEFAULT does not exist inside "/Users/g123k/Library/Application Support/org.GoXLR-on-Linux.GoXLR-Utility/profiles"
13:12:07 [ERROR] Couldn't load mic profile DEFAULT: Mic Profile DEFAULT does not exist inside /Users/g123k/Library/Application Support/org.GoXLR-on-Linux.GoXLR-Utility/mic-profiles
```

What can I do to solve this?

Thanks

**Comment by FrostyCoolSlug** [comment]
Sorry for the delayed response here, I'm gonna need to look into this as when creating the directories it should extract the defaults out, if it can't find a default it'll load an internal one.. That last phase seems to not be working.

It might be worth running `goxlr-defaults mic-profiles /Users/g123k/Library/Application Support/org.GoXLR-on-Linux.GoXLR-Utility/mic-profiles` to forcefully extract the default.

**Comment by FrostyCoolSlug** [comment]
Closing as Stale.
