### ISSUE TITLE
Mixer Level made goxlr-daemon crash

### ISSUE THREAD

**Issue by Desaydrone** [GoXLR-on-Linux/goxlr-utility#57]
Hello,

I got problem with Mixer level in the UI when i change them, goxlr daemon
I made some test and it seems that it arrived only from UI or API, when i change level from fader it doesn't crash

When it crash the deamon take 100% of one core of the cpu

![image](https://user-images.githubusercontent.com/15471688/232182059-3c27f3f5-0ec4-4bf8-b34e-7ac343e1af1e.png)

**Comment by FrostyCoolSlug** [comment]
Could you let me know what version of the util you're running, as well as whether you're using a mini or a full device?

Also, could you run the deamon from a console using `goxlr-daemon --log-level debug` and see if there are any messages spewed when it locks up?

Thanks.

**Comment by Desaydrone** [comment]
Sorry i forget the info : 

Goxlr-utility : 0.10.2 
Goxlr Mini

And sorry but not information in the debug log

[debug_goxlr.txt](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11239710/debug_goxlr.txt)

**Comment by FrostyCoolSlug** [comment]
The log seems to tell me a little bit at least :)

Could you let me know the firmware versions (A screenshot of System -> About should be sufficient)

Thanks

**Comment by Desaydrone** [comment]
If you see something good :-P

![image](https://user-images.githubusercontent.com/15471688/232230341-72531c9a-f84e-4a98-a9e1-8323b0fd2b69.png)

**Comment by FrostyCoolSlug** [comment]
Ok, I've dragged my mini out of storage, and I've been able to reproduce the issue, so I'll try and find out what's going on there :)

**Comment by FrostyCoolSlug** [comment]
Just a quick check, in that debug log, did you first manually move the faders, then move them in the UI causing the lockup? Just making sure I'm not missing something else bad happening :)

**Comment by Desaydrone** [comment]
Yes but for the system fader, the one make goxlr crash is the Music one in the UI, so not the same

**Comment by FrostyCoolSlug** [comment]
Ok, so the good news is that I've actually already fixed this bug, the downside being that it's in a private repository currently (scheduled for merging into 0.11.0), so it should be fixed when 0.11.0 comes along :)

Thanks for the report!

**Comment by Desaydrone** [comment]
Good news !! i could wait no problem :)

**Comment by FrostyCoolSlug** [comment]
This has now been pushed to the dev-0.11.0 branch :)
