### ISSUE TITLE
Missing dependencies for building

### ISSUE THREAD

**Issue by linkian209** [GoXLR-on-Linux/goxlr-utility#59]
When trying to compile on Ubuntu 22.04, I found that `clang` and `libspeechd-dev` are required to compile the `speech-dispatcher` package. Is it worth adding these to the README?

**Comment by FrostyCoolSlug** [comment]
Yea, those will likely come in soon, there's still a bit of movement on the TTS stuff so just wanted everything to settle before updating the readme, I'll keep this open until the README is updated.

**Comment by linkian209** [comment]
Ok. No problem I noticed this because I was trying to figure out why my sample recording wasn't working and discovered this when compiling.

**Comment by FrostyCoolSlug** [comment]
Yea, that's reasonable, the TTS stuff was added yesterday, but it's likely going to be moved to a 'on request' feature, which will remove the clang and libspeechd requirements unless specifically requested, it's mostly just awaiting some code finalisation before making notes (the downsides of building a dev branch unfortunately!)

**Comment by linkian209** [comment]
Yeah, no problem. Completely understand. Thank y'all so much for working on this. I know a little Rust if y'all need help with anyhting.

**Comment by FrostyCoolSlug** [comment]
Ok, the TTS is now an optional feature, so unless compiling `--features tts`, it should no longer have the clang / libspeechd dependency, I'll document enabling this feature separately!

**Comment by FrostyCoolSlug** [comment]
The TTS feature and dependencies are now documented in the README, so I'm going to close this issue as complete.
