### ISSUE TITLE
Allow public bind address from web settings

### ISSUE THREAD

**Issue by timmo001** [GoXLR-on-Linux/goxlr-utility#64]
I'm creating an integration with this application for Home Assistant, and have found that I needed to add ` --http-bind-address 0.0.0.0` to the daemon shortcut to allow remote connections to the API/Websocket.

This isnt the simplest setup and would like to see this in the GUI/Webapp, so others are able to easily allow remote connections

**Comment by FrostyCoolSlug** [comment]
I've been meaning to do this for a while, when the daemon was originally written it was never intended to be accessed outside of localhost, but that changed over time via requests.. The WebUI config has continued to grow since, and would definitely benefit from having a UI panel at this point to allow more fine grained configuration.

I'll look into this for the 0.12 release, while I finish tidying up functionality.

**Comment by Dreamtrailtv** [comment]
I think that for many streamers with a separate streaming setup it can be useful to control the GoXLR with their main setup.

@timmo001: can you post your integration i wanted to do the same and got stuck at the same point :)

**Comment by timmo001** [comment]
> I think that for many streamers with a separate streaming setup it can be useful to control the GoXLR with their main setup.
> 
> @timmo001: can you post your integration i wanted to do the same and got stuck at the same point :)

Will do when its ready to use. Current stage is experimenting and setting up a basic integration

**Comment by Dreamtrailtv** [comment]
> > I think that for many streamers with a separate streaming setup it can be useful to control the GoXLR with their main setup.
> > @timmo001: can you post your integration i wanted to do the same and got stuck at the same point :)
> 
> Will do when its ready to use. Current stage is experimenting and setting up a basic integration

Ich kann mittesten wenn du etwas funktionsfähiges hast

**Comment by timmo001** [comment]
Here's the custom integration [repository](https://github.com/timmo001/homeassistant-integration-goxlr-utility). 

To start with, I have added some basic volume sensors but plan to add more to the integration in the future.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/28114703/235320990-efcd4730-283b-4346-84c8-d7f95b0cb4af.png">

**Comment by FrostyCoolSlug** [comment]
This is implemented in d9873dd6, and is labelled in the settings as 'Allow UI network access' (that may be renamed before release), if checked the UI will bind to all interfaces (0.0.0.0) on startup.

For legacy purposes, if `--http-bind-address` is in use, it will override that setting (and allow more fine-grained settings for those who want it).

**Comment by timmo001** [comment]
Perfect! I'll look forward to the next release 👍
