### ISSUE TITLE
Profile switching does not work in development version 0.12

### ISSUE THREAD

**Issue by Dreamtrailtv** [GoXLR-on-Linux/goxlr-utility#76]
In the current dev version 0.12 profile changing does not work because the web interface uses wrong rest api commands. The complete host part with port is missing.
![image_2023-05-18_194101545](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/51512219/140ad641-e23b-4af0-92a8-2d3bbd08883a)

**Comment by FrostyCoolSlug** [comment]
Thanks for the heads up, I think I've fixed this already in UI repo itself, but I haven't merged the UI into 0.12 recently (it's been undergoing quite a few changes). I'll get this sorted soon.

**Comment by FrostyCoolSlug** [comment]
This should be fixed in eec09c4 - Can you give it a test for me please?

**Comment by Dreamtrailtv** [comment]
It works :)
