### ISSUE TITLE
Fader can't unmute when it is not set to the Hardwarefaders

### ISSUE THREAD

**Issue by Dreamtrailtv** [GoXLR-on-Linux/goxlr-utility#77]
I have a profile that sets the Fader Line In to mute, but if I load a profile that does not set the Fade In Fader as a hardware fader but in the profile it is unmuted, the fader remains on mute. If I set the fader as hardware fader the mute button stays in unmuted status and if you press it then the fader is first muted and with another click unmuted also for routing.

Status with line in on hardware fader:
[statuswithhardwarefader.txt](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11704433/statuswithhardwarefader.txt)

Status with line in without hardware fader:
[statuswithouthardwarefader.txt](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11704435/statuswithouthardwarefader.txt)

Status after manually set Fader Line to a Hardwarefader:
[statusmanuallysetfader.txt](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11704437/statusmanuallysetfader.txt)

Status after switching the mute button on and off:
[statusaftertoggledmutebutton.txt](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11704438/statusaftertoggledmutebutton.txt)

Profile with hardwarefader:
[PC Off.zip](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11704442/PC.Off.zip)

Profile without hardwarefader:
[Standard_Headphones.zip](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11704446/Standard_Headphones.zip)

Debuglog:
[debuglog.txt](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11704452/debuglog.txt)

Driver:
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/51512219/ded20e3f-8269-42f2-9f68-fe120e0e182f)

**Comment by FrostyCoolSlug** [comment]
Thanks for the detailed report, it looks like the hardware side mute state isn't being cleared when a profile is loaded so the old state is persisting.. I'll look into doing some tests and see if I can come up with an elegant solution to that, otherwise I can just force unmute everything before a profile applies.

**Comment by FrostyCoolSlug** [comment]
This should be fixed now in dev-0.12.0, could you give test please and let me know?

**Comment by Dreamtrailtv** [comment]
Funktioniert jetzt danke :)
