### ISSUE TITLE
[Feature] More power state actions 

### ISSUE THREAD

**Issue by Sporesirius** [GoXLR-on-Linux/goxlr-utility#79]
For example, the ability to switch profiles on sleep or hibernate.

**Comment by FrostyCoolSlug** [comment]
Managing behaviours based around power management is somewhat outside the general scope of the project, there are too many different ways to handle the behaviour across multiple distributions, and operating systems.

With that having been said, the `goxlr-client` binary can be used to trigger more advanced behaviours via scripts. For example, I've configured KDE to load different colour profiles when I lock my desktop.

On Lock:  
`goxlr-client profiles device load-colours Sleep` 

On Unlock:  
`goxlr-client profiles device load-colours Frosty`

Depending on how your OS / Distro handles sleep and hibernate, you should be able to kick off a call to `goxlr-client` to handle what you need to handle.

**Comment by Sporesirius** [comment]
Oh nice, unfortunately I don't have a Windows system near me at the moment.

**Comment by Sporesirius** [comment]
Do you want me to test the Linux build?

**Comment by FrostyCoolSlug** [comment]
If you could, that would be great :)

Thanks.

**Comment by FrostyCoolSlug** [comment]
This was added into the 1.0.1 release, so I'll close this as complete.
