### ISSUE TITLE
Sampler LEDs on web interface do not match hardware

### ISSUE THREAD

**Issue by AlienXAXS** [GoXLR-on-Linux/goxlr-utility#85]
Hi,
Please accept my apologies if I am misunderstanding how this replacement software should operate, however I wanted to share a finding:

On the original GoXLR software, clearing a sample would turn off the LED on that button to clearly show that the button has nothing assigned to it - Ready for recording!

It seems goxlr-utility does not do this, even though the web interface shows that the light should be off.

I have the full sized GoXLR, running Windows 11, utility v0.12.1

Here is an image where you can clearly see the software thinks the LED is off, but the GoXLR hardware device still has it on.
![image](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/1773445/a4efca39-8c39-45b9-b6fc-163bfffe6377)

**Comment by FrostyCoolSlug** [comment]
Thanks for the report, it looks like something else has gone wrong either with the visualiser or the utility (none of the colours seem to match correctly).

Could you please change the log level do debug (in system -> settings), restart the utility, try clearing a fader, then attach the log file here please?

Thanks.

**Comment by FrostyCoolSlug** [comment]
Just a couple of extra questions to help track this down, when you do things like mute a fader, change the FX preset and the samples presets, do the buttons correctly light up to represent that?

Finally, what firmware version are you running (can be found on System -> About).

From what I'm seeing, and what you've described, it looks like the utility is failing to apply the colour map to the device. The colours in the UI don't match the colours of the device, and 'blanking' the sampler button requires a full colour map update, which is obviously not happening despite the util thinking it has.

**Comment by AlienXAXS** [comment]
Hi Frosty,
Here is the log file: 
[goxlr-daemon.log](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11926431/goxlr-daemon.log)

This process was:

1. Start the app
2. Add a sample to button A Bottom Right
3. Clear the sample using the Clear button on the GoXLR
4. Colours remained the same.

> When you do things like mute a fader, change the FX preset and the samples presets, do the buttons correctly light up to represent that?
No, changing the colours in the Lighting -> Sampler section does not reflect on the hardware

Firmware Versions:
- Firmware: 1.3.44.105
- Dice: 1.3.9.100
- FPGA: 7

**Comment by FrostyCoolSlug** [comment]
Thanks, does the clear button flash when you press it?

**Comment by AlienXAXS** [comment]
> Thanks, does the clear button flash when you press it?

Yes

**Comment by AlienXAXS** [comment]
If debugging is easier: I am more than happy to jump on a discord call and go through steps, just ask :)

**Comment by FrostyCoolSlug** [comment]
Just saw the edit, thanks.

So definitely something wrong with the colour map, I'll do some checking.

**Comment by FrostyCoolSlug** [comment]
> I believe this could be due to me using the colour effects where the buttons change slowly.

Just to clarify, under the official app, were you using the global animation feature?

**Comment by AlienXAXS** [comment]
Yes bud.
I'm just doing testing now to see if the problem persists if i disable this feature then reload that disabled profile on GoXLR Utility.

**Comment by FrostyCoolSlug** [comment]
Ok, that'll probably do it, the util doesn't support the animations, so the GoXLR might be 'stuck' with them on as the util can't turn them off..

Can you simply unplug your GoXLR from Power, then plug it back in again and see if the util picks the colours up correctly?

**Comment by AlienXAXS** [comment]
Hi,
It seems that loading a no effect profile did the trick, also tried replugging power and that also worked as intended too.

Sorry to have been a pain here, i was not aware the colour animations didnt work.

**Comment by FrostyCoolSlug** [comment]
No problem at all, that's on me. I'll make a small adjustment to the code to force animations off on profile load to ensure this doesn't trip anyone else up.

**Comment by AlienXAXS** [comment]
Sounds perfect, thanks for making the app and the great support :)

**Comment by FrostyCoolSlug** [comment]
This will be fixed for the 1.0 release (7eeb56c).

Thanks again for the report!
