### ISSUE TITLE
GoXLR hardware unresponsive on Chrome on Android

### ISSUE THREAD

**Issue by Gama-Tech** [GoXLR-on-Linux/goxlr-utility#93]
The GoXLR hardware doesn't respond to UI changes when using Chrome on Android using the "remote access" feature of GoXLR Utility.

The GoXLR hardware correctly responds to UI changes when using Firefox on Android, so the issue seems to be unique to Chrome..
However I've not tested any other browsers so the issue may exist on others.

**Comment by FrostyCoolSlug** [comment]
I've been looking into this, I've solved the basic issue that changes aren't represented.. But I'm running into a problem with the sliders themselves.

For whatever reason, when used chrome doesn't 'grab' the sliders handle and move it as you move your finger up and down the bar, firefox seems to handle this flawlessly.. I'm not sure if it's a bug or something else going on.

I'm going to look into some 'special' code for Chromium to try and monitor touch movement events over the slider, and see if I can line up values with the location of the finger.

**Comment by FrostyCoolSlug** [comment]
Ok, this should be fixed for the next release.

**Comment by FrostyCoolSlug** [comment]
https://github.com/GoXLR-on-Linux/goxlr-utility/files/11952711/windows-artifact.zip - Test build here if you're willing to give that a try and let me know if it's working :)

**Comment by FrostyCoolSlug** [comment]
I've got a test release here: [windows-artifact.zip](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11962410/windows-artifact.zip) - Could you give that a try please and let me know if it works correctly?

**Comment by FrostyCoolSlug** [comment]
This has been improved on 0.12.3
