### ISSUE TITLE
[Bug] On Startup GoXLR Utility doesn’t wait for animation.

### ISSUE THREAD

**Issue by teddybrine** [GoXLR-on-Linux/goxlr-utility#96]
When turning off and on your goxlr from the wall, the fancy RGB animation plays with the faders moving up and down. Yet Goxlr Utility starts controlling it half way through this animation, setting my profile faders. This normally makes it so the faders begin at 0.

**Comment by FrostyCoolSlug** [comment]
Thanks for the report, I've actually fought with this slightly on the official app, all the USB functions come up before the calibration has finished which causes the problem, and there's no event or indication sent that the 'setup' is complete. 

What I'll do, is attempt to time the difference between when the device becomes available, and when it becomes usable, and add a short pause in the device loading code to hopefully accommodate for it.

**Comment by FrostyCoolSlug** [comment]
I've added a 1.5 second pause between a GoXLR being found, and it beginnig the profile Load. I have a test build if you'd like to give it a try: [windows-artifact.zip](https://github.com/GoXLR-on-Linux/goxlr-utility/files/11962410/windows-artifact.zip)

**Comment by teddybrine** [comment]
Works like a charm. Cheers.
